import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Responsible AI — TrialLens AI", description: "The intended use, safeguards, limitations and human-oversight principles behind TrialLens AI." };
function Mark(){return <span className="logo-mark" aria-hidden="true"><i></i><i></i><b></b></span>}

const principles=[
  ["Human autonomy","TrialLens informs evidence review; it does not replace a clinical-development team, governance committee or regulator."],
  ["Safety and public interest","Claims that cannot be supported by retrieved metadata are not presented as established efficacy, safety or benefit–risk conclusions."],
  ["Transparency","The product states its sources, retrieval time, automated rules, intended use and limitations where users need them."],
  ["Responsibility and accountability","A qualified person remains accountable for source selection, interpretation, documentation and the final development decision."],
  ["Inclusiveness and equity","Reviewers should examine whether study populations represent relevant ages, sexes, ethnicities, geographies and comorbidities."],
  ["Responsive governance","Source changes, retrieval failures, user feedback and performance issues should be monitored and reflected in product updates."],
];

export default function ResponsibleAI(){return <main className="info-page responsible-page">
  <div className="notice">Live evidence from official sources · Updated on every search</div>
  <header className="site-header"><Link className="logo" href="/"><Mark/><span>TrialLens</span><sup>AI</sup></Link><nav><Link href="/how-it-works">How it works</Link><Link href="/#sources">Sources</Link><Link className="active" href="/responsible-ai">Responsible AI</Link></nav><Link className="header-action" href="/new-review">New review <span>→</span></Link></header>
  <section className="info-hero responsible-hero"><span className="mini-label">RESPONSIBLE AI</span><h1>Useful evidence support.<br/><em>Clear human accountability.</em></h1><p>TrialLens is designed around a simple boundary: software can retrieve and structure evidence, but qualified people must interpret it and own consequential development decisions.</p></section>
  <section className="intended-use"><div><span className="mini-label">INTENDED USE</span><h2>What TrialLens is for</h2><p>Supporting drug-development professionals with discovery, organization and review of publicly available clinical-trial and scientific-literature records.</p></div><div><span className="mini-label">NOT INTENDED FOR</span><h2>What TrialLens must not do</h2><p>Diagnosis, treatment advice, patient-level decisions, autonomous progression decisions, regulatory determinations or unverified clinical claims.</p></div></section>
  <section className="principles-section"><div className="process-intro"><span className="mini-label">GOVERNANCE PRINCIPLES</span><h2>Six commitments for evidence AI</h2><p>Adapted to this research workspace from the World Health Organization’s principles for AI in health.</p></div><div className="principle-grid">{principles.map(([title,copy],i)=><article key={title}><b>0{i+1}</b><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
  <section className="controls-section"><div><span className="mini-label">CONTROL MODEL</span><h2>Safeguards across the review</h2></div><div className="control-list"><article><b>Before retrieval</b><p>The user defines the asset and optional indication. The system makes the active source scope visible.</p></article><article><b>During retrieval</b><p>Records come from identified public APIs; retrieval errors are shown rather than replaced with invented content.</p></article><article><b>At interpretation</b><p>Evidence volume is separated from clinical meaning. Links enable verification against the underlying source.</p></article><article><b>At decision</b><p>Human review is explicit. Exports retain limitations and do not present automated maturity signals as recommendations.</p></article></div></section>
  <section className="limitations"><div><span className="mini-label">KNOWN LIMITATIONS</span><h2>Where caution is required</h2></div><ul><li>Search terms can miss synonyms or retrieve records that are not decision-relevant.</li><li>Registry records may be incomplete, outdated or lack posted results.</li><li>Publication counts do not measure evidence quality, consistency or applicability.</li><li>The current version does not extract full outcome tables or perform validated risk-of-bias assessment.</li><li>External source availability and API changes can affect retrieval.</li></ul></section>
  <section className="guidance-links"><div><span className="mini-label">AUTHORITATIVE GUIDANCE</span><h2>Standards informing the approach</h2></div><div><a href="https://www.who.int/publications/i/item/9789240037403" target="_blank" rel="noreferrer"><b>WHO</b><span>Ethics and governance of artificial intelligence for health</span><em>Read guidance ↗</em></a><a href="https://www.fda.gov/medical-devices/software-medical-device-samd/transparency-machine-learning-enabled-medical-devices-guiding-principles" target="_blank" rel="noreferrer"><b>FDA · Health Canada · MHRA</b><span>Transparency principles emphasizing clear information and the human–AI team</span><em>Read principles ↗</em></a></div></section>
  <footer><Link className="logo" href="/"><Mark/><span>TrialLens</span><sup>AI</sup></Link><p>Evidence → context → human decision</p><span>Decision-support only</span></footer>
  </main>}
